name: Deploy Static

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  deploy:
    name: "Deploy to DigitalOcean"
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/server.key
          chmod 600 ~/.ssh/server.key
          cat >>~/.ssh/config <<END
          Host server
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/server.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{secrets.SSH_USER}}
          SSH_KEY: ${{secrets.SSH_KEY}}
          SSH_HOST: ${{secrets.SSH_HOST}}

      - name: Pull from github
        run: ssh -v server 'cd /repo/ballz-game-clone && git pull'

      - name: Install dependencies
        run: ssh -v server 'npm install'

      - name: Build project
        run: ssh -v server 'npm run build'

      - name: Copy files to deploy folder
        run: ssh -v server 'cp -a /repo/ballz-game-clone/dist. /var/www/ballz/'
